### ISSUE TITLE
Vignette `RowsAndColumns` referenced but doesn't exist

### ISSUE THREAD

**Issue by barryrowlingson** [WinVector/cdata#5]
Help for `pivot_to_rowrecs` references a vignette that doesn;t exist:
```

Description:

     This is a convenience notation for ‘blocks_to_rowrecs’. For a
     tutorial please try ‘vignette('RowsAndColumns', package='cdata')’.
```

```
> vignette('RowsAndColumns', package='cdata')
Warning message:
vignette ‘RowsAndColumns’ not found 
```

Referenced in two places in the roxygen docs:

https://github.com/WinVector/cdata/search?l=R&q=vignette

**Comment by JohnMount** [comment]
Sorry about that, and thanks for reporting.  Looks like the link went bad, I've fixed it it the development version.
