### ISSUE TITLE
performance for input with many columns

### ISSUE THREAD

**Issue by tdhock** [WinVector/cdata#8]
Hi @JohnMount  @NinaZumel first of all thanks for your great package, it is really fascinating and inspiring!

I have been performance testing `cdata::rowrecs_to_blocks`, which seems to be quadratic in the number of input columns to reshape (aka number of rows in the control table), but I expected the timings to be linear. Here is a figure that shows significant slowdowns after about 10,000 input columns:

![figure-iris-cols](https://user-images.githubusercontent.com/932850/67725382-6d470d00-f99f-11e9-907f-d93a2ade2e14.png)

- script to compute timings: https://github.com/tdhock/nc-article/blob/master/figure-iris-cols-data.R
- script to make figures: https://github.com/tdhock/nc-article/blob/master/figure-iris-cols.R

a simplified version of the timings script which only has cdata code is:
```r
N.rep <- 1000
i.vec <- 1:N.rep
L <- lapply(i.vec, function(i)iris[,1:4])
names(L) <- i.vec
L[["0"]] <- iris
some.iris <- do.call(data.frame, L)
part.list <- list()
for(part in c("Petal", "Sepal")){
  part.list[[part]] <- grep(part, names(some.iris), value=TRUE)
}
controlTable.args <- c(list(
  stringsAsFactors=FALSE,
  dim=sub(".Sepal.", "", part.list$Sepal, fixed=TRUE)),
  part.list)
controlTable <- do.call(data.frame, controlTable.args)
system.time({
  result <- cdata::rowrecs_to_blocks(
    some.iris, controlTable=controlTable, columnsToCopy="X0.Species")
})
```
I expected that computation time should be linear in `N.rep` but it appears to be quadratic. To fix that issue you may check into how `data.table` is doing it, because they seem to have implemented a linear time algorithm.

I also checked `unpivot_to_blocks` but that function seems to be linear:
![figure-who-cols-minimal](https://user-images.githubusercontent.com/932850/67726607-a6817c00-f9a3-11e9-99ac-9f55c2f93429.png)

**Comment by JohnMount** [comment]
Definitely an interesting study, thanks for sharing it.  I'll take a look at the runtime, likely we are doing something expensive that can be avoided.  A point is: `cdata` was designed for expressiveness and teaching more than performance, so large structure are a bit of an exception.

**Comment by JohnMount** [comment]
Looks like changing the visibility of a column I was altering has a pretty large performance impact (code [here](https://github.com/WinVector/cdata/commit/16235153b98c2f4c03325339d73334a411228caa#diff-34cacef27e0f4761cee5ac4c135e826d)). I don't expect `cdata` to be fastest, but that should help a lot.

Thanks for your kind note and including a simplified concrete test case.  

I took a look at the package and RJournal article you are working up.  Nice work, please stay in touch.  My email is: `jmount@win-vector.com`.
